
version: '3'
volumes:
    prometheus_data: {}
services:
  pihome:
    image: pihome
    build: .
    restart: always
    #    network_mode: host
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    expose:
      - 5000
        #    ports:
        #      - 5000:5000
    environment:
      - NETWORK_TO_SCAN=${NETWORK_TO_SCAN}
 
  prometheus:
    image: prom/prometheus:v2.36.1
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      #- /var/prometheus:/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'       
        #    ports:
        #      - 9090:9090
    expose:
      - 9090            
    extra_hosts:
      - pihome:${HOST_IP}
    depends_on:
      - pihome
    restart: always

  grafana:
    image: grafana/grafana:8.3.1
    depends_on:
      - prometheus
    expose:
      - 3000            
        #    ports:
        #      - 80:3000
    volumes:
      - ./grafana/:/etc/grafana/
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            
  caddy:
    image: caddy:2.3.0
    container_name: caddy
    depends_on:
      - grafana
    ports:
      - "80:3000"
      - "9090:9090"
      - "5000:5000"
    volumes:
      - ./caddy:/etc/caddy
    env_file:
       ./.env    
    environment:
      - ADMIN_USER=${ADMIN_USER}
     #- ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
    restart: unless-stopped              
